### ISSUE TITLE
Wrong arrow position

### ISSUE THREAD

**Issue by Fafaqqqq** [Fausto-Korpsvart/Catppuccin-GTK-Theme#10]
![image](https://github.com/Fausto-Korpsvart/Catppuccin-GTK-Theme/assets/73164828/28b1037e-8f23-4e9a-acc4-7f9116852e39)

I have a wrong arrow position from WIRED button in drop down menu. How can i fix it?

**Comment by Fausto-Korpsvart** [comment]
> ![image](https://user-images.githubusercontent.com/73164828/260292269-28b1037e-8f23-4e9a-acc4-7f9116852e39.png)
> 
> I have a wrong arrow position from WIRED button in drop down menu. How can i fix it?

Yes, this theme has not yet been updated for compatibility with the latest version of GNOME Shell.
I'm really sorry I haven't updated these themes yet, but my work hasn't allowed me to dedicate as much time as I wanted to this GTK theme project.
I'm working on a way to maintain them the way the creator of the themes I've based them on does, I'm slowly making progress because I only dedicate part of my free time, so I'll update as soon as everything is ready.

Thanks for your support and patience.
