### ISSUE TITLE
Please, catppuccin is NOT only neovim!!

### ISSUE THREAD

**Issue by Taitep** [Fausto-Korpsvart/Catppuccin-GTK-Theme#11]
Catppuccin is the best theme ever, and i see a LOT of things not added to the official repo (https://github.com/catppuccin/catppuccin). Catppuccin already has a gtk theme. If you want to continue, consider adding the icons to the repo's list of ports, or at least expand the theme so that all flavours of catppuccin are accounted for. (REMEMEBER!! I am not the creator of the catppuccin theme, not even a contributor! This is just a reccomendation.)

**Comment by Fausto-Korpsvart** [comment]
> Catppuccin is the best theme ever, and i see a LOT of things not added to the official repo (https://github.com/catppuccin/catppuccin). Catppuccin already has a gtk theme. If you want to continue, consider adding the icons to the repo's list of ports, or at least expand the theme so that all flavours of catppuccin are accounted for. (REMEMEBER!! I am not the creator of the catppuccin theme, not even a contributor! This is just a reccomendation.)

Hi, @Taitep, Thanks for the recommendation.

Well, my project started as personal modifications that later more people liked, this is not part of the official Catppuccin repositories and I don't think it will become part of those official repos, as, due to my work, it is difficult for me to dedicate enough time as I would like to this project; for that reason I prefer to have the project separate from the official repositories to bring the updates to my time.

I am currently working on an update that will make the maintainability of the themes a bit more manageable by modifying the theme directly from the source code, which will allow to have the options to install the different colour versions of the theme, as the creator of the theme I have based it on has done, I know this has taken me more time than I had planned, but it's because of what I mentioned before, my work leaves me little time to dedicate to this project; but once I finish the modifications of the theme, I'll make an update, little by little, of all the themes.

As I said before, thanks for the recommendation and the interest, but for the moment this project won't be part of the official Catppuccine repository, at least until I feel I can dedicate the necessary time; but don't worry, I'll make some updates soon.

**Comment by Taitep** [comment]
I do not mean that, but maybe you could get some others to help maimtain the icon theme and get on there? There are basically no full-catppuccin icon themes in the ports list. I found your project by searching Catppuccin Icon Theme.

**Comment by Fausto-Korpsvart** [comment]
> I do not mean that, but maybe you could get some others to help maintain the icon theme and get on there? There are basically no full-catppuccin icon themes in the ports list. I found your project by searching Catppuccin Icon Theme.

Regarding icons, I haven't spent much time researching icon creation, I really know very little about it, I thought you were referring more to GTK themes.

One thing I had thought about this was to modify the [Colloid](https://github.com/vinceliuice/Colloid-icon-theme) icons to complement the GTK themes, but as I said before, I know very little about it, I have to spend some time to research more about icons.
For the time being the current icons will remain a modification of the [Suru Plus](https://github.com/gusbemacbe/suru-plus) theme, which hasn't been updated for quite some time, so you will understand that I can't put these icons in the official Catppuccin repositories for the reason.

As I said before, I'm focusing on what is priority for me at the moment, which is to support the GTK themes and update them, since it's been a while since the last update, after that I'm planning to do more research on the icon themes to complement, I just need some time and patience to finish everything.

**Comment by Taitep** [comment]
Ok, sorry for this, not a big problem. I just think k you should not make it seem like catppuccin is just a neovim theme and that this is "the" gtk theme for catppuccin.

**Comment by Fausto-Korpsvart** [comment]
> Ok, sorry for this, not a big problem. I just think k you should not make it seem like catppuccin is just a neovim theme and that this is "the" gtk theme for catppuccin.

Don't take this the wrong way, I don't mean to, but I think it's you who sees things that way };-]

As I said before, this project started with modifications to a theme that was for personal use, I have never said or made it seem that Catppuccin is only for Neovim, I have used this and many other colour palettes for Neovim and my desktop environments, I know that it is not limited to just code editors, it is a colour palette that can be adapted to anything, I have even seen rooms with this colour palette, keyboards, etc.

I haven't said or made it seem like my GTK theme is the best or the only one either, in fact I stopped updating the GTK theme for Catppucin because there is already an official theme, and it is very good and has all the variants of its colour palette, and if I have still updated and thought about continuing to update the GTK theme, it is because this is nothing more than an alternative to the official theme.

In fact, [some time ago](https://github.com/Fausto-Korpsvart/Catppuccin-GTK-Theme/issues/1), someone from the Catppuccin project told me that when the theme was ready I should let him know so that the theme could be part of the project, if I haven't done it is because my work doesn't leave me much time to dedicate to this project.

And if I say all this is just to clarify that things are not as you think  };-]
