### ISSUE TITLE
gnome 47 

### ISSUE THREAD

**Issue by Rishabh-Sarang** [Fausto-Korpsvart/Catppuccin-GTK-Theme#29]
accent colors broken

![image](https://github.com/user-attachments/assets/1fe39652-1562-4360-abd0-88263724f3e2)

**Comment by abdellaouiamir** [comment]
Did you manage to fix it? I have the same bug.

**Comment by Rishabh-Sarang** [comment]
only @Fausto-Korpsvart can fix this issue

**Comment by Fausto-Korpsvart** [comment]
This is now fixed, but I still need to make a lot more changes before upgrading, but just know that this is already solved, just a little patience while the upgrade is coming.

**Comment by Fausto-Korpsvart** [comment]
Theme updated!

**Comment by shawnyeager** [comment]
Congrats, @Fausto-Korpsvart. Eagerly awaiting the AUR update.

Have you considered adding GitHub sponsorship? I'd like to support you, but don't have/use Paypal. Cheers.

**Comment by Fausto-Korpsvart** [comment]
> Congrats, @Fausto-Korpsvart. Eagerly awaiting the AUR update.
> 
> Have you considered adding GitHub sponsorship? I'd like to support you, but don't have/use Paypal. Cheers.

Yes, I've been thinking about adding GitHub Sponsors for a while now, due to lack of time I'm more focused on solving problems and I always forget to do it, but soon I will do it, when it happens you'll see.

I really appreciate a lot that you consider supporting the project, it helps to keep going, thanks }:]
